
name: test-selfsigned-certs
on: [push]
env:
  DOCKER_REGISTRY_URL: docker.pkg.github.com
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}

      - name: run action 
        uses: kofemann/action-create-certificate@v0.0.3
        with:
          hostcert: 'hostcert.pem'
          hostkey:  'hostkey.pem'
          cachain: 'ca-chain.pem'

      - name: Output results
        run: |
            echo *
            
      - name: check with openssl
        run: |
            openssl x509 -in hostcert.pem -noout -text
