
name: test-selfsigned-certs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run action 
        uses: kofemann/action-create-certificate@v0.0.3
        with:
          hostcert: 'hostcert.pem'
          hostkey:  'hostkey.pem'
          cachain: 'ca-chain.pem'

      - name: Output results
        run: |
            echo *
            
      - name: check with openssl
        run: |
            openssl x509 -in hostcert.pem -noout -text
