
name: test-selfsigned-certs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run action 
        uses: kofemann/action-create-certificate@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          hostcert: 'hostcert.pem'
          hostkey:  'hostkey.pem'
          cachain: 'ca-chain.pem'

      - name: Output results
        run: |
            echo *
            
      - name: check with openssl
        run: |
            openssl x509 -in hostcert.pem -noout -text
